### ISSUE TITLE
Release for ViT-H/14 (resolution=512) and ViT-L/16 (resolution=518) 

### ISSUE THREAD

**Issue by yuzhenmao** [google-research/vision_transformer#133]
Hi, we didn't find the pre-trained ViT-H/14 model which is mentioned in paper (Section 4.1 Training & Fine-tuning, on page 5). Besides, we found on the same page, it is mentioned that "fine-tuned at higher resolution: 512 for ViT-L/16 and 518 for ViT-H/14". But in the GitHub repo, we only found the pre-trained model with resolution equals 384.

Could you please share the pre-trained ViT-H/14 (resolution=512) and ViT-L/16 (resolution=518)? Thank you very much!

**Comment by dosovits** [comment]
IIRC we're not sharing the H model, since it does not perform very well when trained on ImageNet21k, so we did not want to confuse the users. 

Re resolution - it should be possible to adjust any way you like, it's not fixed per model. The only thing is that the position embeddings need to be reshaped, but this is handled [here](https://github.com/google-research/vision_transformer/blob/main/vit_jax/checkpoint.py#L152)

**Comment by yuzhenmao** [comment]
Thanks for the answer!
