### ISSUE TITLE
Discrepancies with standard transformer architecture 

### ISSUE THREAD

**Issue by kseniaryabinova** [google-research/vision_transformer#253]
Hello and thank you for your work on ViT!

I was writing a blogpost on the ViT architecture and came across the discrepancy with standard Transformer encoder.
As stated in the paper, ViT was developed with the **fewest possible modifications** in Transformer encoder, but I compared Transformer encoder block used in ViT with blocks from "Attention is all you need" and from "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding" and it seems like there is a discrepancy.

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/13572978/212745445-7757e7c7-7378-463b-bc09-f5b607237736.png">

Seems like MHA and the first LayerNorm, and also MLP and the second LayerNorm switched places. And also the skip-connectors are changed positions. 

Why are there so many changes to the Transformer encoder architecture?

**Comment by andsteing** [comment]
Yes indeed, that is a modification:

Even though the original transformer paper [(Vaswani, 2017)] used "post-LN", and this was then used again in the BERT paper [(Devlin, 2018)], later work like [(Baevski, 2018)] and [(Wang, 2019)] (which are mentioned in "3.1 Vision Transformer (ViT)" of our paper) mention that "pre-LN"  often works better, and that's what we use for ViT.

Since our paper, there have been more publications like [(Xiong, 2020)], which explains *why* pre-LN works better, and  [(So, 2022)], which mentions that this has become pretty much standard practice.

[(Vaswani, 2017)]: https://arxiv.org/abs/1706.03762
[(Devlin, 2018)]: http://arxiv.org/abs/1810.04805
[(Baevski, 2018)]: http://arxiv.org/abs/1809.10853
[(Wang, 2019)]: http://arxiv.org/abs/1906.01787
[(Xiong, 2020)]: http://arxiv.org/abs/2002.04745
[(So, 2022)]: http://arxiv.org/abs/2109.08668

**Comment by kseniaryabinova** [comment]
Thank you for your comprehensive response!
